services:
  devtoy-mysql-product:
    image: mysql:8.4.2
    container_name: devtoy-mysql-product
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devtoy_product
      MYSQL_USER: devtoy_product
      MYSQL_PASSWORD: devtoy_product
      TZ: Asia/Seoul
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./docker_volume/mysql/product/data:/var/lib/mysql
      - ./mysql/initdb.d/product:/docker-entrypoint-initdb.d

  devtoy-mysql-order:
    image: mysql:8.4.2
    container_name: devtoy-mysql-order
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devtoy_order
      MYSQL_USER: devtoy_order
      MYSQL_PASSWORD: devtoy_order
      TZ: Asia/Seoul
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./docker_volume/mysql/order/data:/var/lib/mysql
      - ./mysql/initdb.d/order:/docker-entrypoint-initdb.d

  devtoy-mysql-member:
    image: mysql:8.4.2
    container_name: devtoy-mysql-member
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devtoy_member
      MYSQL_USER: devtoy_member
      MYSQL_PASSWORD: devtoy_member
      TZ: Asia/Seoul
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./docker_volume/mysql/member/data:/var/lib/mysql
      - ./mysql/initdb.d/member:/docker-entrypoint-initdb.d

  devtoy-kafka-01:
    image: confluentinc/cp-kafka:7.7.0
    container_name: devtoy-kafka-01
    ports:
      - "9092:9092"
    volumes:
      - ./docker_volume/kafka/devtoy-kafka-01/secrets:/etc/kafka/secrets
      - ./docker_volume/kafka/devtoy-kafka-01/data:/var/lib/kafka/data
    environment:
      CLUSTER_ID: "event-broker"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@devtoy-kafka-01:29092,2@devtoy-kafka-02:29093,3@devtoy-kafka-03:29094"
      KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://devtoy-kafka-01:19092,EXTERNAL://devtoy-kafka-01:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

  devtoy-kafka-02:
    image: confluentinc/cp-kafka:7.7.0
    container_name: devtoy-kafka-02
    ports:
      - "9093:9093"
    volumes:
      - ./docker_volume/kafka/devtoy-kafka-02/secrets:/etc/kafka/secrets
      - ./docker_volume/kafka/devtoy-kafka-02/data:/var/lib/kafka/data
    environment:
      CLUSTER_ID: "event-broker"
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@devtoy-kafka-01:29092,2@devtoy-kafka-02:29093,3@devtoy-kafka-03:29094"
      KAFKA_LISTENERS: "PLAINTEXT://:19093,CONTROLLER://:29093,EXTERNAL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://devtoy-kafka-02:19093,EXTERNAL://devtoy-kafka-02:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

  devtoy-kafka-03:
    image: confluentinc/cp-kafka:7.7.0
    container_name: devtoy-kafka-03
    ports:
      - "9094:9094"
    volumes:
      - ./docker_volume/kafka/devtoy-kafka-03/secrets:/etc/kafka/secrets
      - ./docker_volume/kafka/devtoy-kafka-03/data:/var/lib/kafka/data

    environment:
      CLUSTER_ID: "event-broker"
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@devtoy-kafka-01:29092,2@devtoy-kafka-02:29093,3@devtoy-kafka-03:29094"
      KAFKA_LISTENERS: "PLAINTEXT://:19094,CONTROLLER://:29094,EXTERNAL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://devtoy-kafka-03:19094,EXTERNAL://devtoy-kafka-03:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

  devtoy-kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: devtoy-kafka-ui
    depends_on:
      - devtoy-kafka-01
      - devtoy-kafka-02
      - devtoy-kafka-03
    ports:
      - "9090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: event-broker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: devtoy-kafka-01:19092,devtoy-kafka-02:19093,devtoy-kafka-03:19094

  devtoy-redis:
    image: redis:7.4
    container_name: devtoy-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker_volume/redis/data:/data
      - ./docker_volume/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  devtoy-eureka:
    image: devcci/devtoy-eureka:latest
    pull_policy: always
    container_name: devtoy-eureka
    ports:
      - "8070:8070"
    environment:
      EUREKA_HOST: http://devtoy-eureka

  devtoy-gateway:
    image: devcci/devtoy-gateway:latest
    pull_policy: always
    container_name: devtoy-gateway
    ports:
      - "8080:8080"
    depends_on:
      - devtoy-eureka
    environment:
      EUREKA_URL: http://devtoy-eureka:8070/eureka

  devtoy-product:
    image: devcci/devtoy-product:latest
    pull_policy: always
    restart: on-failure
    environment:
      MYSQL_PRODUCT_HOST: devtoy-mysql-product
      MYSQL_PRODUCT_PORT: 3306
      MYSQL_PRODUCT_DB: devtoy_product
      MYSQL_PRODUCT_USER: devtoy_product
      MYSQL_PRODUCT_PASS: devtoy_product
      KAFKA_BOOTSTRAP_SERVERS: devtoy-kafka-01:9092,devtoy-kafka-02:9093,devtoy-kafka-03:9094
      REDIS_HOST: devtoy-redis
      REDIS_PORT: 6379
      REDIS_PASS: devtoy
      EUREKA_URL: http://devtoy-eureka:8070/eureka
    depends_on:
      - devtoy-gateway
      - devtoy-mysql-product

  devtoy-order:
    image: devcci/devtoy-order:latest
    pull_policy: always
    restart: on-failure
    environment:
      MYSQL_ORDER_HOST: devtoy-mysql-order
      MYSQL_ORDER_PORT: 3306
      MYSQL_ORDER_DB: devtoy_order
      MYSQL_ORDER_USER: devtoy_order
      MYSQL_ORDER_PASS: devtoy_order
      KAFKA_BOOTSTRAP_SERVERS: devtoy-kafka-01:9092,devtoy-kafka-02:9093,devtoy-kafka-03:9094
      REDIS_HOST: devtoy-redis
      REDIS_PORT: 6379
      REDIS_PASS: devtoy
      EUREKA_URL: http://devtoy-eureka:8070/eureka
    depends_on:
      - devtoy-gateway
      - devtoy-mysql-order

  devtoy-member:
    image: devcci/devtoy-member:latest
    pull_policy: always
    restart: on-failure
    environment:
      MYSQL_MEMBER_HOST: devtoy-mysql-member
      MYSQL_MEMBER_PORT: 3306
      MYSQL_MEMBER_DB: devtoy_member
      MYSQL_MEMBER_USER: devtoy_member
      MYSQL_MEMBER_PASS: devtoy_member
      REDIS_HOST: devtoy-redis
      REDIS_PORT: 6379
      REDIS_PASS: devtoy
      EUREKA_URL: http://devtoy-eureka:8070/eureka
    depends_on:
      - devtoy-gateway
      - devtoy-mysql-member
