spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: devtoy-eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost}:${server.port}/eureka/
server:
  port: ${SERVER_EUREKA_PORT:8070}

