# devtoy-member

###
# @name 회원가입
POST {{server-gateway}}/auth
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "memberId": "tester4",
  "password": "test1234",
  "name": "테스트",
  "email": "tester4@gmail.com",
  "role": [
    "admin",
    "member"
  ]
}

###
# @name 로그인
GET {{server-gateway}}/auth
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "memberId": "tester1",
  "password": "test1234"
}

> {%
    //response handler
    client.global.set("token", response.body.accessToken);
    client.log("token : " + client.global.get("token"));
%}

###
# @name 회원 전체 조회
GET {{server-gateway}}/member
Authorization: Bearer {{token}}