# devtoy-product

###
# @name 카테고리별최저가상품
GET {{server-gateway}}/product/categories/lowest

###
# @name 최저가브랜드
GET {{server-gateway}}/product/brands/lowest

###
# @name 카테고리 최고/최저가
GET {{server-product}}/product/categories/min-max-prices?
    categoryName=상의

###
# @name 브랜드 리스트
GET {{server-gateway}}/brands

###
# @name 브랜드 추가
POST {{server-product}}/brands
Content-Type: application/json

{
  "brandName": "새브랜드1"
}

###
# @name 브랜드 수정
PUT {{server-product}}/brands
Content-Type: application/json

{
  "brandId": 1,
  "brandName": "새브랜드2"
}

###
# @name 브랜드 삭제
DELETE {{server-product}}/brands/10

###
# @name 상품 리스트
GET {{server-product}}/product?
    page=1&
    size=100&
    sort=asc

###
# @name 상품 추가
POST {{server-product}}/product
Content-Type: application/json

{
  "productName": "새거야새거",
  "brandName": "새브랜드1",
  "categoryName": "상의",
  "price": 50511
}

###
# @name 상품 수정
PUT {{server-product}}/product
Content-Type: application/json

{
  "productId": 1,
  "productName": "상품",
  "brandName": "A",
  "categoryName": "상의",
  "price": 11200,
  "description": "상품"
}

###
# @name 상품 삭제
DELETE {{server-product}}/product/4