spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: devtoy-gateway
  cloud:
    gateway:
      routes:
        - id: devtoy-product
          uri: lb://DEVTOY-PRODUCT
          predicates:
            - Path=/products/**, /brands/**
        #          filters:
        #            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id: devtoy-member
          uri: lb://DEVTOY-MEMBER
          predicates:
            - Path=/member/**,/auth/**
        #          filters:
        #            - RewritePath=/member/(?<segment>.*), /$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka}

server:
  port: ${SERVER_GATEWAY_PORT:8080}
