spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: devtoy-gateway
  cloud:
    gateway:
      routes:
        - id: devtoy-product
          uri: lb://DEVTOY-PRODUCT
          predicates:
            - Path=/product/**, /brand/**
        #          filters:
        #            - RewritePath=/product/(?<segment>.*), /$\{segment}
        - id: devtoy-member
          uri: lb://DEVTOY-MEMBER
          predicates:
            - Path=/member/**,/auth/**
        #          filters:
        #            - RewritePath=/member/(?<segment>.*), /$\{segment}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${SERVER_GATEWAY_PORT:8080}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    use-root-path: true
    path: /swagger-ui/index.html
    urls:
      - url: /product/v3/api-docs
        name: product
      - url: /member/v3/api-docs
        name: member