# default mysql db
spring:
  application:
    name: devtoy-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_MEMBER_HOST:localhost}:${MYSQL_MEMBER_PORT:3308}/${MYSQL_MEMBER_DB:devtoy_member}
    username: ${MYSQL_MEMBER_USER:devtoy_member}
    password: ${MYSQL_MEMBER_PASS:devtoy_member}
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:devtoy}

jwt:
  secret-key: ${JWT_SECRET_KEY:5bbb92ebf0d8443754b7cc85b8c2f8983ee6a074e191fbec8b1efb33379f92dd0d3b0ba4d96e161c0250f5f60f4f35c8c4b8e7291e92f37649bf9123e2b340c7}}
  expire-time-hour: 1
  refresh-expire-time-hour: 24

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka}
    registry-fetch-interval-seconds: 5
    disable-delta: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${SERVER_MEMBER_PORT:8083}
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /v3/api-docs/member
  swagger-ui:
    use-root-path: true

# h2 db
---
spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devtoy-member
    username: sa
    password:
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# Integration Test - TestContainers
---
spring:
  config:
    activate:
      on-profile: integrationTest
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

eureka:
  client:
    enabled: false

# 외부서버
---
spring:
  config:
    activate:
      on-profile: external
    import: optional:file:.env[.properties]
