# default mysql db
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: devtoy-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_MEMBER_HOST:localhost}:${MYSQL_MEMBER_PORT:3307}/${MYSQL_MEMBER_DB:devtoy_member}
    username: ${MYSQL_MEMBER_USER:devtoy}
    password: ${MYSQL_MEMBER_PASS:devtoy}
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:devtoy}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expire-time-hour: 1
  refresh-expire-time-hour: 24

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka}

server:
  port: ${SERVER_MEMBER_PORT:8082}
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

# h2 db
---
spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devtoy-member
    username: sa
    password:
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# Integration Test - TestContainers
---
spring:
  config:
    activate:
      on-profile: integrationTest
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true