# default mysql db
spring:
  application:
    name: devtoy-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_PRODUCT_HOST:localhost}:${MYSQL_PRODUCT_PORT:3306}/${MYSQL_PRODUCT_DB:devtoy_product}
    username: ${MYSQL_PRODUCT_USER:devtoy_product}
    password: ${MYSQL_PRODUCT_PASS:devtoy_product}
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:devtoy}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
    consumer:
      group-id: devtoy-product-group

topic:
  order:
    create: devtoy-order-create
    result: devtoy-order-result

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka}
    registry-fetch-interval-seconds: 5
    disable-delta: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${SERVER_PRODUCT_PORT:8081}
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /v3/api-docs/product
  swagger-ui:
    use-root-path: true


# h2 db
---
spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devtoy-product
    username: sa
    password:
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


# Integration Test - TestContainers
---
spring:
  config:
    activate:
      on-profile: integrationTest
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    enabled: false


# 외부서버
---
spring:
  config:
    activate:
      on-profile: external
    import: optional:file:.env[.properties]
