spring:
  application:
    name: devtoy-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ORDER_HOST:localhost}:${MYSQL_ORDER_PORT:3307}/${MYSQL_ORDER_DB:devtoy_order}
    username: ${MYSQL_ORDER_USER:devtoy_order}
    password: ${MYSQL_ORDER_PASS:devtoy_order}
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:devtoy}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}

topic:
  order:
    create: devtoy-order-create
    fail: devtoy-order-fail

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8070/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: ${SERVER_ORDER_PORT:8082}
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /v3/api-docs/order
  swagger-ui:
    use-root-path: true


# Integration Test - TestContainers
---
spring:
  config:
    activate:
      on-profile: integrationTest
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

kafka:
  enabled: false

eureka:
  client:
    enabled: false

# 외부서버
---
spring:
  config:
    activate:
      on-profile: external
    import: optional:file:.env[.properties]
